package com.model;

/**
 * com.model.Loan
 *
 * Autogenerated constructors, getter e setter espliciti.
 */
public class Loan {

    private Integer codeProduct;
    private Integer quantity;
    private Integer discount;
    private Double unitPrice;
    private Double totalImport;
    private String status;

    public Loan() {
    }

    public Loan(Integer codeProduct, Integer quantity) {
        this.codeProduct = codeProduct;
        this.quantity = quantity;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getCodeProduct() {
        return codeProduct;
    }

    public void setCodeProduct(Integer codeProduct) {
        this.codeProduct = codeProduct;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getDiscount() {
        return discount;
    }

    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Double getTotalImport() {
        return totalImport;
    }

    public void setTotalImport(Double totalImport) {
        this.totalImport = totalImport;
    }
}